### ISSUE TITLE
Where is Doom workshop located?

### ISSUE THREAD

**Issue by Blueberryy** [Varheel/SteamWorkshopUploader#1]
I can't find Steam Workshop for Doom games but this uploader looks interesting

**Comment by Varheel** [comment]
This is for any Doom/GZDoom game that's available on Steam and has the Workshop enabled so players can upload mods.
Basically, you run this program and select your WAD file, it uploads to Steam, then other players can subscribe to your mod.

As far as I know, there is only one game on Steam right now that supports this:
[I Am Sakuya: Touhou FPS Game](https://store.steampowered.com/app/1960590/I_Am_Sakuya_Touhou_FPS_Game/)

But other game developers could publish a Doom game on Steam and use this [and my other project](https://github.com/Varheel/gzdoom-sws) to enable mods.
